### ISSUE TITLE
Asrock B660M Phantom Gaming 4

### ISSUE THREAD

**Issue by joeboxer62** [dclive/B660M-HDV---i5-1200F#1]
At first,  
thank you for your tutorial.
You have inspired my build, all is working but the Lan.
Do you have ethernet working fine?

Kind thanks

**Comment by dclive** [comment]
It's the same I219V as the B660M-HDV.  It should work flawlessly...

**Comment by joeboxer62** [comment]
Hi, thanks, so you do not use Mausiethernet or other kext, just the Apple OS. Fine. hope to solve

**Comment by joeboxer62** [comment]
About your M2 NVME [ADATA 8200 Pro] can you refer what speed do you have? 
I have about 5GB/s read 4GB/s write - Crucial Plus 500

**Comment by dclive** [comment]
> Hi, thanks, so you do not use Mausiethernet or other kext, just the Apple OS. Fine. hope to solve

You may wish to download the zipfile again, because intelmausi.kext is certainly in there.  Are you using my EFI or someone else's?

**Comment by dclive** [comment]
> About your M2 NVME [ADATA 8200 Pro] can you refer what speed do you have? I have about 5GB/s read 4GB/s write - Crucial Plus 500

This will depend on NVME SSD used, motherboard settings, and many other factors.  I'd say your speed is in a good range.

**Comment by dclive** [comment]
- Closing as resolved, IntelMausi.kext is in the zipfile and satisfies for Intel 219V Ethernet -

**Comment by joeboxer62** [comment]
Sorry, I was using a different version, I just roll back to your and I confirm your mausi.kext works perfectly! Thank you again.
