### ISSUE TITLE
Is this a correct usb according to the instructions?

### ISSUE THREAD

**Issue by nam0107** [dclive/B660M-HDV---i5-1200F#3]
<img width="722" alt="Screen Shot 2022-08-07 at 00 13 10" src="https://user-images.githubusercontent.com/45630755/183259123-eab223dd-8c48-4194-9d1d-06d28eeac586.png">

**Comment by dclive** [comment]
No, it isn't. Please see the paragraph starting with "Download EFIAgent " and follow those steps.  

Broadly, MacOS installer (the picture you show) is one partition (a non-hidden partition), and the EFI/EPS partition, a hidden partition, is another.  The files in the Zip go into a folder on the EFI/EPS partition.  You'll find and mount this partition with EFI Agent.

**Comment by nam0107** [comment]
<img width="426" alt="Screen Shot 2022-08-07 at 00 32 58" src="https://user-images.githubusercontent.com/45630755/183259702-d1328a90-931e-40db-b5be-2292066a333d.png">
So I can find the EFI/EPS partition with EFI Agent.

**Comment by dclive** [comment]
There it is.  Simply mount that EFI and then you can copy the zip file to that efi.  You'll want the EFI that's the same as your USB that you are installing from; I assume that to be disk3.  Thus you'd mount the EFI 2nd from the bottom, disk3s1, and then copy the zip file onto that.

**Comment by dclive** [comment]
On second look, it looks like the "Install macOS Monterey" USB stick is actually disk2, but for some reason no EFI was made for that USB stick.  That's a problem.  How did you make that USB stick?

**Comment by dclive** [comment]
Broadly speaking, this really isn't a problem. You can put the EFI folder onto any EPS/EFI disk, including the "Shared Support" USB stick.  It would then let you boot, would scan your drives, _should_ find the Monterey USB install disk (disk2s1), and let you boot the installer from there. 

But for your own sanity and learning, it's best to have everything on one disk while initially discovering how this stuff works, so I'd suggest removing any excess USB sticks, focusing on the Monterey USB stick, and getting that working.

**Comment by nam0107** [comment]
I'm not sure it is disk3 because if I eject my USB, the disk3 still there :
<img width="422" alt="Screen Shot 2022-08-07 at 00 48 09" src="https://user-images.githubusercontent.com/45630755/183260173-a917143c-0970-4f26-9583-5aec846efa44.png">
(

**Comment by dclive** [comment]
Yes, please see my later comments.

**Comment by nam0107** [comment]
<img width="893" alt="Screen Shot 2022-08-07 at 00 51 28" src="https://user-images.githubusercontent.com/45630755/183260288-42bf7de9-58cd-4a3d-97b2-8a07beb009df.png">
This is my way to make USB stick

**Comment by nam0107** [comment]
I only run this command to create USB stick, is it right ?

**Comment by dclive** [comment]
Yes, that's all you should need to do in order to make a working USB stick (with a working EFI partition).  If that doesn't make an EFI partition, I'm not sure what to say.  It normally does.  My initial guess is you didn't format the disk with the GUID format via Disk Utility.  For more information, see here:  https://www.tonymacx86.com/threads/create-efi-partition.306067/

**Comment by dclive** [comment]
Did you have any other questions?  Did you try reformatting your USB stick in GUID, HFS+ format?

**Comment by nam0107** [comment]
Thanks for you hepl, I created the USB stick, installed macos success but after that I can't boot in macos

**Comment by dclive** [comment]
Why not?  I need full information, details, screenshots of what you do and what happens.

**Comment by nam0107** [comment]
Do you have any chat acc or skype, anything else I will connect with you

**Comment by nam0107** [comment]
hoainamtrinh98@gmail.com
this is my email, you can send chat acc though it, I will connect with you

**Comment by dclive** [comment]
If you post here, everyone can learn, and I can also update my docs when problems are found.  You'll note that I updated my docs to show that a format of the USB stick with GUID is required (thank you!).

**Comment by nam0107** [comment]
I created USB stick, format my disk which I chose to install MacOs to "Mac OS Extended (Journaled) and for Scheme choose "GUID Partition Map, then select install MacOs, after install, my computer restart and I can't boot in my USB or my disk
this is video for this
https://drive.google.com/file/d/1NJ3KIXmo2NZiiVR6MfJQLRPzoNjauCcz/view?usp=sharing

**Comment by dclive** [comment]
I see.  Thanks for uploading; that's a good video.

What BIOS version? 
Did you disable VT-d in BIOS? 
Did you disable serial port in BIOS? 
Did you disable CSM?

**Comment by nam0107** [comment]
this is my step
![IMG_2007](https://user-images.githubusercontent.com/45630755/183295319-c7337a69-a26c-4206-b1eb-6b43098e435e.jpg)
![IMG_2010](https://user-images.githubusercontent.com/45630755/183295343-6104e619-43d9-4391-8627-ff73180eebd9.jpg)

![IMG_2008](https://user-images.githubusercontent.com/45630755/183295339-59287b82-ca43-4ebc-9b27-9c341a19a47b.jpg)
![IMG_2009](https://user-images.githubusercontent.com/45630755/183295341-870e640f-6a9a-4233-9fe4-aef2cf52b7eb.jpg)

**Comment by dclive** [comment]
The questions I asked are BIOS questions.  Go into your BIOS and confirm those settings.

**Comment by nam0107** [comment]
I'm using B660M Pro Rs 5.0, I disabled VT-d and CSM but I can't find the serial port in my BIOS config
![IMG_2012](https://user-images.githubusercontent.com/45630755/183295837-a82462e3-dd2c-491b-9efc-9c31feb7873d.jpg)

![IMG_2011](https://user-images.githubusercontent.com/45630755/183295831-ef04cf19-a0bb-4886-8590-fa8305d996ab.jpg)
4

**Comment by dclive** [comment]
Disable CAM (Clever Access Memory) and try again.

**Comment by nam0107** [comment]
I'm trying reinstall again after Disable CAM (Clever Access Memory)

**Comment by nam0107** [comment]
maybe the problem is caused by me creating USB stick from USB 3.0 ?

**Comment by dclive** [comment]
You don't need to reinstall MacOS.  MacOS is on the SSD.  If you can't boot from the USB stick and then see a boot menu with the installed MacOS being a choice, that's what we need to troubleshoot.  

The fact that you can boot from USB and fully install MacOS means that the installation phase of this works fine. 

USB could be the problem, and you're welcomed to try that USB stick in a USB2.0-only port (a black port, usually).  That's a completely different motherboard, so it's likely your USB will need to be remapped once you're in MacOS,

Better for this troubleshooting:  DIsable CAM, then shoot another video of what happens when you boot from USB.

**Comment by nam0107** [comment]
oke let me try

**Comment by dclive** [comment]
Again, MacOS is partially/somewhat installed now.  You need to boot from USB, select the MacOS partition you installed (usually "MAC HD" or "Monterey", but NOT "Install MacOS Monterey" !!!) and let bootup / setup continue.

**Comment by nam0107** [comment]
I boot from usb again but cant see the MAC HD
![IMG_2013](https://user-images.githubusercontent.com/45630755/183297156-9cc81e4e-599f-4045-bc65-f5cbfdcf064d.jpg)

**Comment by dclive** [comment]
Boot from the one on the right and let's see what happens.  Perhaps you renamed your SSD to that name when you were setting things up.

**Comment by nam0107** [comment]
I try to boot into the one on the right, it happen same the video I send before

**Comment by dclive** [comment]
OK.  You're using a different motherboard so unfortunately there's not much I can do.  Between "different motherboard" and "different BIOS settings" there are a lot of variables.  If you want, you're welcomed to take another video showing the full bootup sequence and I'll try to freeze the video at the exact point where it reboots (I enabled logging, so I think it shows the full details) so we can try to see what is wrong. 

So - send another video.

**Comment by dclive** [comment]
And CAM is disabled, right?

**Comment by nam0107** [comment]
yes CAM is disabled

**Comment by dclive** [comment]
Super IO Configuration
- Serial Port: Disabled
- Parallel Port: Disabled

All that's done?  Or you simply do not have a SuperIO section in your BIOS?

**Comment by dclive** [comment]
Also - please describe all hardware in the machine.  Everything.  Including BIOS version.  I don't care about PSU, case, or RAM.  Tell me everything else.

**Comment by nam0107** [comment]
In Super IO Configuration section I don't have Serial Port and Parallel Port

**Comment by dclive** [comment]
https://www.reddit.com/r/hackintosh/comments/p5hezn/big_sur_115_stuck_at_eblogresetrecovery_use/ is very, very similar.  Serial ports, parallel ports disable seems to have helped, and then they had to DISABLE above 4G decoding (whereas in most modern machines, one enables it) so... try flipping that setting too.

**Comment by nam0107** [comment]
My pc using:
i5 - 12400F
Asrock B660M Pro RS 5.04
RX 570 saphire 4GB

**Comment by dclive** [comment]
Making a wild guess based on your email, but does this help at all?  https://voz.vn/t/thanh-qua-hackintosh-cua-anh-em.8792/page-56

**Comment by dclive** [comment]
Do you have a feature in BIOS to disable CFG LOCK ?

**Comment by nam0107** [comment]
yes I disabled CFG LOC

**Comment by dclive** [comment]
https://voz.vn/t/thanh-qua-hackintosh-cua-anh-em.8792/page-62 looks to me like someone 's saying for B660M RS Pro use... there's a OC download file there.  Oddly, it has i3-12300F details but the Mac is being told it's an i5-7500 or somesuch, so it's a bizarre setup, but if it works...

**Comment by nam0107** [comment]
okie let me try ^^

**Comment by dclive** [comment]
I've made some significant changes and updated to the latest OC.  You're welcomed to re-test.

**Comment by nam0107** [comment]
oke thank you ^^

**Comment by dclive** [comment]
What happened ?

**Comment by nam0107** [comment]
I use the new OC you pushed but the same issue like my video @@

**Comment by nam0107** [comment]
I will try to create USB stick with a 2.0 usb instead of 3.0 usb

**Comment by dclive** [comment]
Please send a new video from the new OC83 EFI.  We need to see what's causing the current reboot problem.  

I wouldn't bother with changing USB sticks.  The only thing that USB stick is doing is booting the EFI/EPS partition.

**Comment by dclive** [comment]
I'll leave this open another day, then close if we don't hear from you...

**Comment by nam0107** [comment]
sorry I haven't been able to try it because I've been busy these past few days, I'll try it as soon as possible
